### ISSUE TITLE
'rows' mode

### ISSUE THREAD

**Issue by alexxxnf** [erdogant/ismember#1]
Hi Erdogan,

Thank you for your work! The function works really well.

However it seems to me the ‘rows’ mode is a bit odd.

I tested these matrices in Matlab:
```
>> a = [1 2 3; 4 5 6; 7 8 9; 10 11 12]

a =

     1     2     3
     4     5     6
     7     8     9
    10    11    12

>> b = [4 5 6; 7 8 0]

b =

     4     5     6
     7     8     0

>> [Lia, Locb] = ismember(a, b, 'rows')

Lia =

  4×1 logical array

   0
   1
   0
   0


Locb =

     0
     1
     0
     0
```

Same code in Python throws an exception.
```
>>> a = np.array((
...     (1, 2, 3),
...     (4, 5, 6),
...     (7, 8, 9),
...     (10, 11, 12),
... ))
>>> b = np.array((
...     (4, 5, 6),
...     (7, 8, 0),
... ))
>>> ismember(a, b, 'rows')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/env/lib/python3.6/site-packages/ismember/ismember.py", line 47, in ismember
    if a_vec.shape[0]!=b_vec.shape[0]: raise Exception('Error: Input matrices should have same number of columns.')
Exception: Error: Input matrices should have same number of columns.
```
Transposing the matrices gives something, but it doesn't match the result from Matlab.
```
>>> Lia, Locb = ismember(a.T, b.T, 'rows')
>>> Lia
(array([False,  True,  True, False]), array([False,  True,  True, False]), array([False,  True, False, False]))
>>> Locb
(array([0, 1]), array([0, 1]), array([0]))
```
I am not an expert in NumPy or Matlab. Maybe I'm doing something wrong.

**Comment by erdogant** [comment]
Thanks for noticing!

I fixed the functionality of 'rows'.
Update with:

`pip install -U ismember`
Version should be >= 0.2.1

```
from ismember import ismember
a_vec = np.array(((1, 2, 3), (4, 5, 6), (7, 8, 9), (10, 11, 12)))
b_vec = np.array(((4, 5, 6), (7, 8, 0)))
Lia, Locb = ismember(a_vec, b_vec, 'rows')

print(Lia)
# [False, True, False, False])
print(Locb)
# [nan,  1., nan, nan]

```

**Comment by alexxxnf** [comment]
Thank you for the quick fix!

I gave it a shot. It’s is getting better - but it’s not quite there yet. I see 2 issues.

According to the [Matlab docs](https://www.mathworks.com/help/matlab/ref/double.ismember.html#d123e721008), "Locb contains the lowest index in B for each value in A that is a member of B." So, in the example above `Locb` should contain `0` instead of `1`, because `0` is the index of `(4, 5, 6)` in `b_vec`.

Another issue is about the type of elements in `Locb`. Since they are indices, they should be integers. Right now they are floats. It leads to the following error:
```
>>> b_vec[Locb]
IndexError: arrays used as indices must be of integer (or boolean) type
```
That happens because `nan` in NumPy is float.

I took the liberty and tried to create a fix based off of your code. My code is very cumbersome, but maybe it’ll help. I completely omitted missing values, since I don’t have better ideas on how to deal with `nan`s.

```Python
def _row_wise(a_vec, b_vec):
    def is_row_in(a, b):
        return np.all(a[:, None] == b, axis=2).any(axis=1)

    bool_ind = is_row_in(a_vec, b_vec)
    common = a_vec[bool_ind]
    [common_unique, common_inv] = np.unique(common, return_inverse=True, axis=0)
    [b_unique, b_ind] = np.unique(b_vec, return_index=True, axis=0)
    common_ind = b_ind[is_row_in(b_unique, common_unique)]

    return bool_ind, common_ind[common_inv]
```

**Comment by erdogant** [comment]
Nice! Indeed, I pushed to fast. I did find your solution quite elegant!

```
pip install -U ismember
import ismember
print(ismember.__version__)


```Version should be >= 0.2.1

btw, I also did not handle the missing values. It is an issue for another day.

**Comment by alexxxnf** [comment]
Thanks a lot!
